## Provides the implementation of the C entry point, whose shape is dependent
## on the target OS, subsystem, and build mode.

proc nimMain() {.cdecl, importc: "NimMain".}
  ## The NimSkull entry-point, generated by the compiler.

# important: the procedures here are run in a pre-boot environment (i.e., the
# runtime hasn't been loaded yet) and must thus not use any feature relying on
# the runtime
{.push checks: off, stacktrace: off.}

# TODO: use proper NimSkull-level-exported globals instead of this
#       exportc/importc workaround
var
  cmdCount {.exportc, noinit.}: cint
  cmdLine {.exportc, noinit.}: cstringArray

when defined(windows) and (appType == "gui" or appType == "lib"):
  type
    HINSTANCE {.importc, header: "<windows.h>".} = object
    LPSTR {.importc, header: "<windows.h>".} = object
    DWORD {.importc, header: "<windows.h>".} = int

  when appType == "gui":
    proc c_entry(curr, prev: HINSTANCE, cmdLine: LPSTR, cmdShow: cint): cint {.
        compilerproc, extern: "WinMain", stdcall.} =
      return cint(programResult)
  else:
    let DLL_PROCESS_ATTACH {.importc, header: "<windows.h>".}: DWORD

    proc c_entry(inst: HINSTANCE, fwdreason: DWORD, reserved: pointer): cint {.
        compilerproc, extern: "DllMain", stdcall.} =
      if fwdreason == DLL_PROCESS_ATTACH:
        # TODO: calling `nimMain` from 'DllMain' is a bad idea, as there are
        #       quite a few restrictions on what is allowed in 'DllMain'
        #       (refer to https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices),
        #       but without this being explicit nor obvious to library code.
        #       It'd be better if the context loading the dynamic library
        #       handles calling the entry point instead
        nimMain()
      return 1

elif appType == "lib":
  # on non-Windows system, use the GCC constructor facility for running the
  # shared object's entry point
  {.emit: "/*PROCSECTION*/void NIM_POSIX_INIT NimMainInit() { `nimMain`() }".}

  proc c_entry() {.compilerproc, importc: "NimMainInit", noconv.}

elif hostOS == "standalone":
  # standalone entry point
  proc c_entry(): cint {.compilerproc, extern: "main", noconv.} =
    nimMain()
    return 0

else:
  proc c_entry(argc: cint, args: cstringArray): cint {.
      compilerproc, extern: "main", noconv.} =
    cmdCount = argc
    cmdLine = args
    nimMain()
    return cint(programResult)

{.pop.}
