name: Download compiler workspace
description: Download the compiler uploaded by upload-compiler
inputs:
  workspace:
    description: Where to extract the compiler
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: compiler ${{ runner.os }} ${{ runner.arch }}
        path: "${{ runner.temp }}"

    - name: Unpack the workspace
      run: |
        import os
        import tarfile
        from pathlib import Path

        archivepath = Path(os.environ["RUNNER_TEMP"]) / "compiler.tar"
        with tarfile.open(archivepath) as archive:
          archive.extractall()
      shell: python3 {0}
      working-directory: "${{ inputs.workspace }}"
