## Implements the entry point into the C code generator.

import
  std/[
    os
  ],
  compiler/ast/[
    ast_types,
    lineinfos
  ],
  compiler/backend/[
    cgbackend,
    cgen,
    cgir2,
    extccomp
  ],
  compiler/front/[
    options,
    msgs
  ],
  compiler/modules/[
    modulegraphs
  ],
  compiler/sem/[
    modulelowering
  ],
  compiler/utils/[
    nversion,
    pathutils,
    platform,
    ropes,
    tracer
  ]

# XXX: reports are a legacy facility that is going to be phased out
from compiler/ast/reports import ReportKind
from compiler/ast/report_enums import rsemCannotOpenFile
from compiler/ast/reports_sem import SemReport, reportStr
from compiler/ast/reports_backend import BackendReport

from compiler/sem/passes import moduleHasChanged

proc writeModule(g: ModuleGraph, m: PSym, code: Rope, cfile: Cfile): bool =
  ## If necessary, writes `code` to `cfile`, returning whether the C file
  ## changed.
  if optForceFullMake notin g.config.globalOptions:
    if not moduleHasChanged(g, m):
      result = false
    elif not equalsFile(code, cfile.cname):
      if not writeRope(code, cfile.cname):
        localReport(g.config, reportStr(rsemCannotOpenFile, cfile.cname.string))

      result = true
    elif fileExists(cfile.obj) and
         fileNewer(cfile.obj.string, cfile.cname.string):
      result = false
    else:
      result = true
  else:
    if not writeRope(code, cfile.cname):
      localReport(g.config, reportStr(rsemCannotOpenFile, cfile.cname.string))

    result = true

proc initCfile(g: ModuleGraph, m: PSym): Cfile =
  let filename = AbsoluteFile toFullPath(g.config, m.position.FileIndex)
  let cfile = changeFileExt(completeCfilePath(g.config, withPackageName(g.config, filename)), ".nim.c")
  Cfile(
    nimname: m.name.s,
    cname: cfile,
    obj: completeCfilePath(g.config, toObjFile(g.config, cfile)),
    flags: {}
  )

proc writeModule(g: ModuleGraph, m: PSym, cfile: sink Cfile, code: string) =
  if code != "" or g.config.symbolFiles != disabledSf:
    if not writeModule(g, m, code, cfile):
      cfile.flags = {CfileFlag.Cached}

    addFileToCompile(g.config, cfile)

proc generateCode*(g: ModuleGraph, mlist: sink ModuleList) =
  ## Entry point into the C code generator. Generates the C code for the whole
  ## (live) program, writing all modified and new C files to disk.
  if optTlsEmulation in g.config.globalOptions:
    globalReport(g.config,
      BackendReport(kind: rbackTlsEmulationNotImplemented))
  if optGenIndex in g.config.globalOptions:
    localReport(g.config,
      BackendReport(kind: rbackHeaderGenerationNotImplemented))

  # the main work is delegated to the generic code generator
  var (m, modules) = cgbackend.generateCode(g, mlist, {})
  resetForBackend(g) # free some memory that's not needed beyond this point

  var preamble = "/* Generated by NimSkull Compiler v$1 */\n" %
                 [VersionAsString]
  if optCompileOnly notin g.config.globalOptions:
    preamble.addf("/* Compiled for: $1, $2, $3 */\n",
      [$platform.OS[g.config.target.targetOS].name,
        $platform.CPU[g.config.target.targetCPU].name,
        $extccomp.CC[g.config.cCompiler].name])

  var defines = "#define NIM_INTBITS "
  defines.addInt platform.CPU[g.config.target.targetCPU].intSize
  defines.add "\n"
  if g.config.isDefined("nimEmulateOverflowChecks"):
    defines.add "#define NIM_EmulateOverflowChecks\n"

  # TODO: re-implement support for header generation

  for it in modules.mitems:
    let v = block:
      g.config.timeTracer.traceStr("scan")
      initModuleDesc(m, it.procs, it.globals, it.emits)

    let cfile = initCfile(g, it.sym)
    var header = preamble
    if optCompileOnly notin g.config.globalOptions:
      header.addf("/* Command for C compiler:\n   $1 */\n",
                  [getCompileCFileCmd(g.config, cfile)])
    header.add defines

    let code = block:
      g.config.timeTracer.traceSym(tikCodegen, it.sym)
      moduleToC(m, v, header, optLineDir in g.config.options)

    writeModule(g, it.sym, cfile, code)

  writeMapping(g.config, "")
