name: Upload the compiler workspace
description: Upload the built compiler for re-use by other jobs
inputs:
  workspace:
    description: What to upload
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Package workspace
      run: |
        # Package new and changed files
        declare -a diff
        while IFS= read -r -d '' file; do
          diff+=("$file")
        done < <(git ls-files -zmo)
        tar cf "$RUNNER_TEMP/compiler.tar" "${diff[@]}"
      shell: bash
      working-directory: "${{ inputs.source }}"

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: compiler ${{ runner.os }}
        path: "${{ runner.temp }}/compiler.tar"
        # This action is only used to share data between jobs, there is no need
        # to keep this artifact for long.
        retention-days: 1
        if-no-files-found: error
