name: Upload the compiler workspace
description: Upload the built compiler for re-use by other jobs
inputs:
  workspace:
    description: What to upload
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Package workspace
      run: |
        import os
        import tarfile
        from pathlib import Path
        from subprocess import run, PIPE

        diff = run(["git", "ls-files", "-zmo"], stdout=PIPE, check=True).stdout.split(b"\0")
        diff = [f.decode() for f in diff if f] # trim empty strings and decode into str

        archivepath = Path(os.environ["RUNNER_TEMP"]) / "compiler.tar"
        with tarfile.open(archivepath, mode="x") as archive:
          for file in diff:
            archive.add(file)
      shell: python3 {0}
      working-directory: "${{ inputs.source }}"

    - uses: actions/upload-artifact@v4
      with:
        name: compiler ${{ runner.os }} ${{ runner.arch }}
        path: "${{ runner.temp }}/compiler.tar"
        # This action is only used to share data between jobs, there is no need
        # to keep this artifact for long.
        retention-days: 1
        if-no-files-found: error
