const
  OSSL_KEYMGMT_SELECT_PRIVATE_KEY* = 0x01
  OSSL_KEYMGMT_SELECT_PUBLIC_KEY* = 0x02
  OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS* = 0x04
  OSSL_KEYMGMT_SELECT_OTHER_PARAMETERS* = 0x80
  OSSL_KEYMGMT_SELECT_ALL_PARAMETERS* = OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS or OSSL_KEYMGMT_SELECT_OTHER_PARAMETERS
  OSSL_KEYMGMT_SELECT_KEYPAIR* = OSSL_KEYMGMT_SELECT_PRIVATE_KEY or OSSL_KEYMGMT_SELECT_PUBLIC_KEY
  OSSL_KEYMGMT_SELECT_ALL* = OSSL_KEYMGMT_SELECT_KEYPAIR or OSSL_KEYMGMT_SELECT_ALL_PARAMETERS
